version: '3'

services:
  db:
    image: mysql:8.3.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q98#946,nFwC$~Oxhc@
      MYSQL_DATABASE: hurlingstat_db
      MYSQL_USER: django
      MYSQL_PASSWORD: q98#946,nFwC$~Oxhc@

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_hstat.settings
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

volumes:
  mysql_data:
