# Generated by Django 5.0.2 on 2024-03-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_UID', models.AutoField(primary_key=True, serialize=False)),
                ('player_first_name', models.CharField(max_length=50)),
                ('player_second_name', models.CharField(max_length=50)),
                ('player_number', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='hstat.team')),
            ],
        ),
    ]
