# Generated by Django 5.0.2 on 2024-03-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hstat', '0002_team_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
