# Generated by Django 5.0.2 on 2024-03-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hstat', '0004_team_player_delete_players_delete_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_team',
            new_name='player_team_id',
        ),
    ]
