# Generated by Django 5.0.2 on 2024-03-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstat', '0007_match_matchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
